DROP TABLE SZEMELY cascade constraints;
DROP TABLE SZAK cascade constraints;
DROP TABLE TEREM cascade constraints; 
DROP TABLE KURZUS cascade constraints;
DROP TABLE VIZSGA cascade constraints;
DROP TABLE TANITJA cascade constraints;
DROP TABLE HALLGATJA cascade constraints;
DROP TABLE FORUM cascade constraints;
DROP TABLE VIZSGAZIK cascade constraints;
DROP SEQUENCE VIZSGAAI;
DROP SEQUENCE KURZUSAI;

CREATE TABLE SZEMELY(
    EHA VARCHAR2(11) PRIMARY KEY,
    Nev VARCHAR2(250) NOT NULL,
    Szuletesi_datum DATE NOT NULL,
    Cim VARCHAR2(250) NOT NULL,
    Jelszo1 VARCHAR2(250) NOT NULL,
	Jelszo NUMBER,
	tipus NUMBER NOT NULL
);

CREATE TABLE SZAK(
    EHA VARCHAR2(11) REFERENCES SZEMELY(EHA) ON DELETE CASCADE,
    Szaknev VARCHAR2(250),
    PRIMARY KEY (EHA, Szaknev)
);

CREATE TABLE TEREM(
    Teremkod VARCHAR2(20) PRIMARY KEY,
    Nev VARCHAR2(250) NOT NULL,
    Kapacitas NUMBER(5) NOT NULL
);

CREATE TABLE KURZUS(
    Kurzuskod VARCHAR2(20) PRIMARY KEY,
    Nev VARCHAR2(250) NOT NULL,
    Het_napja VARCHAR2(10) NOT NULL,
    Mettol VARCHAR2(5) NOT NULL,
    Meddig VARCHAR2(5) NOT NULL,
    Kredit NUMBER(2) DEFAULT 0 NOT NULL,
    Teremkod VARCHAR2(20),
	Eloadasa VARCHAR2(20),
	FOREIGN KEY (Teremkod) REFERENCES TEREM(Teremkod) ON DELETE SET NULL,
    FOREIGN KEY (Eloadasa) REFERENCES KURZUS(Kurzuskod) ON DELETE CASCADE
);

CREATE TABLE VIZSGA(
    Vizsgakod VARCHAR2(20) PRIMARY KEY,
    Kurzuskod VARCHAR2(20) NOT NULL,
    Idopont TIMESTAMP NOT NULL,
    Teremkod VARCHAR2(20),
    Ar NUMBER(5) DEFAULT 0 NOT NULL,
    FOREIGN KEY (Teremkod) REFERENCES TEREM(Teremkod) ON DELETE SET NULL,
    FOREIGN KEY (Kurzuskod) REFERENCES KURZUS(Kurzuskod) ON DELETE CASCADE
);

CREATE TABLE TANITJA(
    EHA VARCHAR2(11),
    Kurzuskod VARCHAR2(20),
    PRIMARY KEY (EHA, Kurzuskod),
    FOREIGN KEY (EHA) REFERENCES SZEMELY(EHA) ON DELETE CASCADE,
    FOREIGN KEY (Kurzuskod) REFERENCES KURZUS(Kurzuskod) ON DELETE CASCADE
);

CREATE TABLE HALLGATJA(
    EHA VARCHAR2(11),
    Kurzuskod VARCHAR2(20),
    Osztalyzat NUMBER(1),
    Felvetel_idopontja DATE NOT NULL,
    PRIMARY KEY (EHA, Kurzuskod),
    FOREIGN KEY (EHA) REFERENCES SZEMELY(EHA) ON DELETE CASCADE,
    FOREIGN KEY (Kurzuskod) REFERENCES KURZUS(Kurzuskod) ON DELETE CASCADE
);

CREATE TABLE FORUM(
    EHA VARCHAR2(11),
    Kurzuskod VARCHAR2(20),
    Mikor TIMESTAMP NOT NULL,
    Uzenet VARCHAR2(250) NOT NULL,
    PRIMARY KEY (EHA, Kurzuskod, Mikor),
    FOREIGN KEY (EHA) REFERENCES SZEMELY(EHA) ON DELETE SET NULL,
    FOREIGN KEY (Kurzuskod) REFERENCES KURZUS(Kurzuskod) ON DELETE CASCADE
);

CREATE TABLE VIZSGAZIK(
    EHA VARCHAR2(11),
    Vizsgakod VARCHAR2(20),
    Vizsgajegy NUMBER(1),
    PRIMARY KEY (EHA, Vizsgakod),
    FOREIGN KEY (EHA) REFERENCES SZEMELY(EHA) ON DELETE CASCADE,
    FOREIGN KEY (Vizsgakod) REFERENCES VIZSGA(Vizsgakod) ON DELETE CASCADE
);

CREATE SEQUENCE  KURZUSAI
  MINVALUE 1
  MAXVALUE 1000
  INCREMENT BY 1 START WITH 1;
  
CREATE SEQUENCE  VIZSGAAI
  MINVALUE 1
  MAXVALUE 1000
  INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER VIZSGATRIGGER
BEFORE INSERT ON VIZSGA
FOR EACH ROW
BEGIN
    :NEW.vizsgakod := VIZSGAAI.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER KURZUSTRIGGER
BEFORE INSERT ON KURZUS
FOR EACH ROW
BEGIN
    :NEW.kurzuskod := KURZUSAI.NEXTVAL;
END;
/

create or replace TRIGGER vizsgajegy
AFTER UPDATE ON vizsgazik
FOR EACH ROW
DECLARE
    exam VIZSGA.KURZUSKOD%TYPE;
BEGIN
    SELECT vizsga.KURZUSKOD INTO exam
    FROM vizsga 
    WHERE VIZSGAKOD = :NEW.vizsgakod;
    UPDATE hallgatja SET osztalyzat = :NEW.vizsgajegy WHERE eha = :NEW.eha AND kurzuskod = exam;
END;
/
